name: "💡 New feature request"
description: "Request a new feature"
title: "[💡 New feature] (Add title here)"
labels: ["💡 New"]
projects: ["RubenTheCoder/4"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our project
  - type: input
    attributes:
      label: What kind of idea is it?
      description: How would you describe your suggestion?
      placeholder: Add your idea here
  - type: textarea
    id: suggestion-text
    attributes:
      label: Describe in more details what it looks like
      description: Write down as detailed as you can, so we can fully understand your idea
      placeholder: Describe here what the idea looks like in detail
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/RubenTheCoder/Shunji-Railways-GitHub/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
